name: Test API
on: [workflow_dispatch]

jobs:
  test-api:
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    services:
        app:
          image: kurmanbek10/simple-node-api
          # ports:
          #   - 3001:3000
          env:
            MONGO_HOSTNAME: mongo
        mongo:
          image: mongo
          # ports: 
          #   - 27017:27017
    steps:
      - name: Install Curl
        run: |
          apt-get -y update
          apt-get -y install curl
      - name: Dump Services Context
        run: echo '${{ toJson(job.services) }}'
      - name: Post a new user
        run: 'curl -X POST http://app:3000/api/users -H ''Content-type: application/json'' -d ''{"username": "hello", "address": "Chicago"}'''
      - name: Get Users
        run: curl http://app:3000/api/users